### ISSUE TITLE
[FEATURE]: Capacity output in storage pool and volume modules

### ISSUE THREAD

**Issue by stevencook2** [dell/ansible-powerflex#11]
**Describe the solution you'd like**
I would like capacity details to be listed in the info module or Storage_pool/Volume modules.

**Describe alternatives you've considered**
Using SRM for capacity details currently.

**Comment by kuttattz** [comment]
@stevencook2  Can you please specify which all capacity details are you expecting to be listed under info module or Storage_pool/Volume modules.

**Comment by stevencook2** [comment]
something along the lines of (for SP module) Pool Usable (in Terabytes), Pool Free (in Terabytes), Pool Usage percent, Pool Subscribed. (for volume module) Volume Name,  Storage pool, Protection Domain, throughput,Bandwidth, and latency.

**Comment by anupamaloke** [comment]
Closed by #18
