### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by OA72280** [dell/ansible-powerflex#30]
https://github.com/dell/ansible-powerflex/blob/main/roles/powerflex_sdc/README.md#:~:text=sdc_test%0A%20%20%20%20%20%20powerflex_sdc_performance_profile%3A%20Compact-,sdc_state%3A%20present,-%2D%20name%3A%20%22Uninstall%20powerflex

I believe sdc_state: present is supposed to be powerflex_sdc_state: ? upon adding in my playbook it seemed to be ok.

      port: "{{ port }}"
      powerflex_common_file_install_location: "/opt/scaleio/rpm"
      powerflex_sdc_name: sdc_test
      powerflex_sdc_performance_profile: Compact
      sdc_state:** present

**Comment by anupamaloke** [comment]
@OA72280 , thank you for submitting the issue. I have added it to the backlog

**Comment by Jennifer-John** [comment]
Fixed as part of #32
