### ISSUE TITLE
[FEATURE]: Rocky_Linux

### ISSUE THREAD

**Issue by OA72280** [dell/ansible-powerflex#31]
It would be helpful to add Rocky_Linux to the operating systems supported.

**Comment by anupamaloke** [comment]
@OA72280 , thanks for submitting the feature request. We will accordingly triage and add it to the backlog for future releases.

**Comment by Bhavneet-Sharma** [comment]
Closing the issue as we have added the support for Rocky Linux in latest release [2.0.1](https://github.com/dell/ansible-powerflex/pull/35).
